/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progressbar;

import java.awt.Cursor;
import java.awt.Point;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import zombie.world.Juego;

/**
 *
 * @author Alan
 */
public class BarraDeCarga extends javax.swing.JFrame {
  /*hacer el cursos diferente*/
    Cursor cursor;
    ImageIcon img = new ImageIcon(getClass().getResource("/imagenes/EspadaImperial.png"));
    Toolkit TK = Toolkit.getDefaultToolkit();
    
    public BarraDeCarga() {
          //Cambiar icono
         this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/mano.png")).getImage());
        
        initComponents();
          /*parte del cursor diferente*/
        this.cursor = TK.createCustomCursor(img.getImage(), new Point(1, 1), "Cursor");
        this.setCursor(cursor);
        
                        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int num = 1; num <= 100; num++) {
                    try {
                        jb_progreso.AumentoDeProgreso(num);
                        jb_progreso.repaint();
                        Thread.sleep(200);
                    } 
                    catch (InterruptedException ex) {
                        Logger.getLogger(BarraDeCarga.class.getName()).log(Level.SEVERE, null, ex);
                    }
                if (num==1){
                TxtA.setText("Existen 5 factores para poder sobrevivir: \n"+
                        "Agua \nComida \nMedicina \nCombustible \nMunicion");
                } else if (num==25){
                TxtA.setText("El agua y la comida son primordiales para\n la"
                +" supervivencia, sin ellas podrias morir");
                } else if (num==50){
                TxtA.setText("El conocer gente te ayudara a contruir una comunidad\n"
                +"grande, pero costara mas mantener los recursos");
                } else if (num==75){
                TxtA.setText("RECUERDA, ¡NO ERES EL UNICO SOBREVIVIENTE!\n"
                        + "podrias toparte no solo con gente buena sino tmabien\n"
                        + "mala");
                }
                
                if (num==100){
                Ventana();}
                }
            }
        }).start();
     this.setLocationRelativeTo(null);
    }
    
    public void Ventana() {
    Juego y = new Juego();
    y.setVisible(true);
    this.dispose();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TxtA = new javax.swing.JTextArea();
        jb_progreso = new progressbar.PanelPersonalizado();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cargado.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 340));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        TxtA.setEditable(false);
        TxtA.setBackground(new java.awt.Color(0, 0, 0));
        TxtA.setColumns(20);
        TxtA.setForeground(new java.awt.Color(255, 255, 255));
        TxtA.setLineWrap(true);
        TxtA.setRows(5);
        TxtA.setBorder(null);
        TxtA.setCaretColor(new java.awt.Color(255, 255, 255));
        TxtA.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        jb_progreso.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jb_progresoLayout = new javax.swing.GroupLayout(jb_progreso);
        jb_progreso.setLayout(jb_progresoLayout);
        jb_progresoLayout.setHorizontalGroup(
            jb_progresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        jb_progresoLayout.setVerticalGroup(
            jb_progresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jb_progreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtA, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 300, Short.MAX_VALUE)
                .addComponent(jb_progreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TxtA, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 640, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TxtA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private progressbar.PanelPersonalizado jb_progreso;
    // End of variables declaration//GEN-END:variables
}
