/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visualizacion;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static zombie.world.Registros.getConecction;

/**
 *
 * @author Garabato
 */
public class Viaje extends javax.swing.JFrame {
    //conexion a mysql

    public static final String URL = "jdbc:mysql://localhost:3306/zombieworld?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC";
    public static final String USERNAME = "root";
    public static final String PASSWORD = "root";

    public Viaje() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        //Cambiar icono
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/mano.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TfC = new javax.swing.JTextField();
        TfMe = new javax.swing.JTextField();
        TfCom = new javax.swing.JTextField();
        TfMu = new javax.swing.JTextField();
        TfA = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Ir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 110, -1));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel2.setText("Lugares");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 70, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa", "Hospital", "Mansion", "Refugio", "Ciudad" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 110, 20));

        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Recursos a Encontrar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 180, -1));

        jButton3.setText("Generar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Combustible");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 120, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Municion");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 100, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Agua");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 60, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 0));
        jLabel7.setText("Comida");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 80, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Medicina");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 80, -1));

        TfC.setEditable(false);
        getContentPane().add(TfC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 70, -1));

        TfMe.setEditable(false);
        getContentPane().add(TfMe, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 70, -1));

        TfCom.setEditable(false);
        getContentPane().add(TfCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 70, -1));

        TfMu.setEditable(false);
        getContentPane().add(TfMu, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 70, -1));

        TfA.setEditable(false);
        getContentPane().add(TfA, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 70, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Viajar.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String viaje = jComboBox1.getSelectedItem().toString();
        if (viaje == "Casa") {
            int Random;
            Random = (int) (Math.random() * 5) + 1;
            switch (Random) {
                case 1:
                    Casa c = new Casa();
                    c.setVisible(true);
                    break;
                case 2:
                    Casa2 c2 = new Casa2();
                    c2.setVisible(true);
                    break;
                case 3:
                    Casa3 c3 = new Casa3();
                    c3.setVisible(true);
                    break;
                case 4:
                    Casa4 c4 = new Casa4();
                    c4.setVisible(true);
                    break;
                case 5:
                    Casa5 c5 = new Casa5();
                    c5.setVisible(true);
                    break;
            }
        } else if (viaje == "Hospital") {
            int Random;
            Random = (int) (Math.random() * 5) + 1;
            switch (Random) {
                case 1:
                    Hospital c = new Hospital();
                    c.setVisible(true);
                    break;
                case 2:
                    Hospital2 c2 = new Hospital2();
                    c2.setVisible(true);
                    break;
                case 3:
                    Hospital3 c3 = new Hospital3();
                    c3.setVisible(true);
                    break;
                case 4:
                    Hospital4 c4 = new Hospital4();
                    c4.setVisible(true);
                    break;
                case 5:
                    Hospital5 c5 = new Hospital5();
                    c5.setVisible(true);
                    break;
            }

        } else if (viaje == "Mansion") {
            int Random;
            Random = (int) (Math.random() * 3) + 1;
            switch (Random) {
                case 1:
                    Mansion c = new Mansion();
                    c.setVisible(true);
                    break;
                case 2:
                    Mansion2 c2 = new Mansion2();
                    c2.setVisible(true);
                    break;
                case 3:
                    Mansion3 c3 = new Mansion3();
                    c3.setVisible(true);
                    break;
            }

        } else if (viaje == "Refugio") {
            int Random;
            Random = (int) (Math.random() * 3) + 1;
            switch (Random) {
                case 1:
                    Refugio c = new Refugio();
                    c.setVisible(true);
                    break;
                case 2:
                    Refugio2 c2 = new Refugio2();
                    c2.setVisible(true);
                    break;
                case 3:
                    Refugio3 c3 = new Refugio3();
                    c3.setVisible(true);
                    break;
            }

        } else if (viaje == "Ciudad") {
            int Random;
            Random = (int) (Math.random() * 2) + 1;
            switch (Random) {
                case 1:
                    Ciudad c = new Ciudad();
                    c.setVisible(true);
                    break;
                case 2:
                    Ciudad2 c2 = new Ciudad2();
                    c2.setVisible(true);
                    break;
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//CHECAR SI YA FUNCIONA 
        try {

            PreparedStatement ps = null;
            ResultSet rs = null;
            Connection con = getConecction();
            CallableStatement CS;
            CS = con.prepareCall("call Generar_Recursos");
            rs = CS.executeQuery(); //LE AGREGUE ESTE :V
            try {
                CallableStatement CS2;
                CS2 = con.prepareCall("select Agua,Comida,Combustible,Municion,Medicina from insumos order by id_cont desc limit 1");
                rs = CS2.executeQuery();

                if (rs.next()) {
                    TfA.setText(rs.getString("Agua"));
                    TfC.setText(rs.getString("Comida"));
                    TfMe.setText(rs.getString("Medicina"));
                    TfCom.setText(rs.getString("Combustible"));
                    TfMu.setText(rs.getString("Municion"));
                }
            } catch (SQLException ex) {
                System.out.println(ex.toString());
            }

        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Viaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TfA;
    private javax.swing.JTextField TfC;
    private javax.swing.JTextField TfCom;
    private javax.swing.JTextField TfMe;
    private javax.swing.JTextField TfMu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
