/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zombie.world;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Garabato
 */
public class CrearPersonaje extends javax.swing.JFrame {

    //conexion a mysql
    public static final String URL = "jdbc:mysql://localhost:3306/zombieworld?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC";
    public static final String USERNAME = "root";
    public static final String PASSWORD = "root";
    PreparedStatement PS;

    /*    JFileChooser selecionar = new JFileChooser();
    File archivo = new File(selecionar.getSelectedFile() + ".txt");
    FileInputStream entrada;
    FileOutputStream salida;*/

 /*hacer el cursos diferente*/
    Cursor cursor;
    ImageIcon img = new ImageIcon(getClass().getResource("/imagenes/EspadaImperial.png"));
    Toolkit TK = Toolkit.getDefaultToolkit();

    public CrearPersonaje() {
        //Cambiar icono
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/mano.png")).getImage());
        initComponents();
        /*parte del cursor diferente*/
        this.cursor = TK.createCustomCursor(img.getImage(), new Point(1, 1), "Cursor");
        this.setCursor(cursor);
        this.setLocationRelativeTo(null);//centrar ventanas        
    }

    /*public String GuargarArchivo(File archivo, String documento) {
    String mensaje = null;
    try {
    salida = new FileOutputStream(archivo);
    byte[] bytxt = documento.getBytes();
    salida.write(bytxt);
    mensaje = "Archivo Guardado";
    } catch (Exception e) {
    }
    return mensaje;
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Txtf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Txtf2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Txtf3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Txtf4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Cb = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        Txtf5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        G = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Cb2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 120));

        Txtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtfActionPerformed(evt);
            }
        });
        Txtf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtfKeyPressed(evt);
            }
        });
        getContentPane().add(Txtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 190, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Edad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 40, -1));

        Txtf2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txtf2KeyPressed(evt);
            }
        });
        getContentPane().add(Txtf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 40, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ciudad de origen");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 130, -1));

        Txtf3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txtf3KeyPressed(evt);
            }
        });
        getContentPane().add(Txtf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 140, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha de Nacimiento");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 170, -1));

        Txtf4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txtf4KeyPressed(evt);
            }
        });
        getContentPane().add(Txtf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 190, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sexo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        Cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));
        getContentPane().add(Cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));

        jLabel7.setText("Estatura");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        Txtf5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txtf5KeyPressed(evt);
            }
        });
        getContentPane().add(Txtf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 140, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nombre");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 70, -1));

        G.setText("Guardar");
        G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GActionPerformed(evt);
            }
        });
        getContentPane().add(G, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, -1, -1));

        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Estado");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        Cb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero", "Casado", "Divorciado", "Viudo", "Comprometido", "Union Libre", "Noviazgo" }));
        getContentPane().add(Cb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1330980685_6914362941_86ca6ff18a_b.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txtf4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txtf4KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Txtf5.requestFocus();
            Txtf5.setBackground(Color.green);
            Txtf3.setBackground(Color.WHITE);
            Txtf2.setBackground(Color.white);
            Txtf.setBackground(Color.white);
            Txtf5.setBackground(Color.white);
        }
    }//GEN-LAST:event_Txtf4KeyPressed

    private void TxtfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtfKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Txtf2.requestFocus();
            Txtf2.setBackground(Color.green);
            Txtf3.setBackground(Color.WHITE);
            Txtf4.setBackground(Color.white);
            Txtf.setBackground(Color.white);
            Txtf5.setBackground(Color.white);
        }
    }//GEN-LAST:event_TxtfKeyPressed

    private void Txtf3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txtf3KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Txtf4.requestFocus();
            Txtf4.setBackground(Color.green);
            Txtf3.setBackground(Color.WHITE);
            Txtf2.setBackground(Color.white);
            Txtf.setBackground(Color.white);
            Txtf5.setBackground(Color.white);

        }
    }//GEN-LAST:event_Txtf3KeyPressed

    private void Txtf5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txtf5KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            CrearPersonaje2 CP = new CrearPersonaje2();
            CP.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_Txtf5KeyPressed

    private void Txtf2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txtf2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Txtf3.requestFocus();
            Txtf3.setBackground(Color.green);
            Txtf2.setBackground(Color.WHITE);
            Txtf4.setBackground(Color.white);
            Txtf.setBackground(Color.white);
            Txtf5.setBackground(Color.white);

        }
    }//GEN-LAST:event_Txtf2KeyPressed

    private void GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GActionPerformed
        Connection con = null;

        try {

            con = getConecction();

            PS = con.prepareStatement("Insert into Personaje(nombre,edad,ciudad_de_origen,fecha_nacimiento,"
                    + "sexo,estatura,estado_civil) Values(?,?,?,?,?,?,?) ");
            PS.setString(1, Txtf.getText());
            PS.setString(2, Txtf2.getText());
            PS.setString(3, Txtf3.getText());
            PS.setString(4, Txtf4.getText());
            PS.setString(5, Cb.getSelectedItem().toString());
            PS.setString(6, Txtf5.getText());
            PS.setString(7, Cb2.getSelectedItem().toString());

            int Res = PS.executeUpdate();

            if (Res > 0) {
                JOptionPane.showMessageDialog(null, "Personaje Guardado");
                LimpiarCajas();
            } else {
                JOptionPane.showMessageDialog(null, "Error al Guardadar Personaje");
                LimpiarCajas();

            }

            con.close();
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
        }
        
         try{ 
            con = getConecction();
            ResultSet res;
            
            PreparedStatement PS;
            
            PS = con.prepareStatement("SELECT * FROM Personaje ORDER BY id_personaje desc");
            res = PS.executeQuery();
        
            if(res.next()){
                JOptionPane.showMessageDialog(null,"Tu Identificador del Pesonaje es = " +res.getString("id_personaje"));
            
            } else {
            JOptionPane.showMessageDialog(null, "No existen datos");
                    
            }
            con.close();
        }
        catch(Exception e){
            System.out.println(e);
        }
 /*  if (selecionar.showDialog(null, "Guardar") == JFileChooser.APPROVE_OPTION) {
        archivo = selecionar.getSelectedFile();
        //if(archivo.getName().endsWith("txt")){
        String Documento = "Nombre: " + Txtf.getText() + "\n" + "Edad: " + Txtf2.getText() + "\n" + "Ciudad de Origen: " + Txtf3.getText() + "\n"
        + "Fecha de Nacimiento: " + Txtf4.getText() + "\n"+ "Sexo: " + Cb.getSelectedItem().toString() + " Estatura: " + Txtf5.getText() +"\n"+
        "Estado civil: "+Cb2.getSelectedItem().toString();
        //este es el que guarda :P
        String mensaje = GuargarArchivo(archivo, Documento);
        if (mensaje != null) {
        JOptionPane.showMessageDialog(null, mensaje);
        } else {
        JOptionPane.showMessageDialog(null, "Archivo No Compatible");
        }
        
        }*/
    }//GEN-LAST:event_GActionPerformed

    public static Connection getConecction() {
        Connection con = null;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(URL, USERNAME, PASSWORD);

        } catch (Exception ex) {
            System.out.println(ex);
        }
        return con;
    }

    private void LimpiarCajas() {
        Txtf.setText("");
        Txtf2.setText("");
        Txtf3.setText("");
        Txtf4.setText("");
        Cb.setSelectedIndex(0);
        Txtf5.setText("");
        Cb2.setSelectedIndex(0);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CrearPersonaje2 CP = new CrearPersonaje2();
        CP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TxtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearPersonaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cb;
    private javax.swing.JComboBox<String> Cb2;
    private javax.swing.JButton G;
    private javax.swing.JTextField Txtf;
    private javax.swing.JTextField Txtf2;
    private javax.swing.JTextField Txtf3;
    private javax.swing.JTextField Txtf4;
    private javax.swing.JTextField Txtf5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
