/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zombie.world;

import java.awt.Image;
import progressbar.BarraDeCarga;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.Icon;

/**
 *
 * @author Garabato
 */
public class Informacion extends javax.swing.JFrame {

    /*    JFileChooser selecionar = new JFileChooser();
    File archivo = new File(selecionar.getSelectedFile() + ".txt");
    FileInputStream entrada;
    FileOutputStream salida;*/
    //conexion a mysql
    public static final String URL = "jdbc:mysql://localhost:3306/zombieworld?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC";
    public static final String USERNAME = "root";
    public static final String PASSWORD = "root";
     PreparedStatement ps = null;
            ResultSet rs = null;

    public Informacion() {
        //Cambiar icono
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/mano.png")).getImage());
        this.setLocationRelativeTo(null);
        initComponents();
         ImageIcon imagen = new ImageIcon(getClass().getResource("/imagenes/Bosque2.jpg"));
        Icon Fondo = new ImageIcon(imagen.getImage().getScaledInstance(this.Fondo.getWidth(), this.Fondo.getHeight(), Image.SCALE_DEFAULT));
        this.Fondo.setIcon(Fondo);
        this.repaint();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /*
    public String AbrirArchivo(File archivo) {
    String documento = "";
    try {
    entrada = new FileInputStream(archivo);
    int a;
    while ((a = entrada.read()) != -1) {
    char caracter = (char) a;
    documento += caracter;
    }
    } catch (Exception e) {
    }
    return documento;
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TxtA3 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtA = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        TxtA4 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        TxtA2 = new javax.swing.JTextArea();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Tf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Tf1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Tf2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Tf3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtA3.setColumns(20);
        TxtA3.setRows(5);
        jScrollPane1.setViewportView(TxtA3);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, 320, 560));

        TxtA.setColumns(20);
        TxtA.setRows(5);
        jScrollPane2.setViewportView(TxtA);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 320, 560));

        TxtA4.setColumns(20);
        TxtA4.setRows(5);
        jScrollPane4.setViewportView(TxtA4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 50, 320, 560));

        jButton1.setText("Abrir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 659, -1, -1));

        jButton2.setText("Abrir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 659, -1, -1));

        jButton4.setText("Abrir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1061, 659, -1, -1));

        jButton7.setText("Abrir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 659, -1, -1));

        TxtA2.setColumns(20);
        TxtA2.setRows(5);
        jScrollPane8.setViewportView(TxtA2);

        getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 320, 560));

        jButton9.setText("Comenzar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 660, -1, -1));

        jLabel1.setFont(new java.awt.Font("Juice ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("Personaje 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 144, 32));

        jLabel2.setFont(new java.awt.Font("Juice ITC", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Personaje 2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 144, 32));

        jLabel3.setFont(new java.awt.Font("Juice ITC", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("Personaje 3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 144, 32));

        jLabel4.setFont(new java.awt.Font("Juice ITC", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Personaje 4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, 144, 32));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID del Personaje");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, -1, -1));
        getContentPane().add(Tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 628, 164, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID del Personaje");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 630, -1, -1));
        getContentPane().add(Tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 628, 164, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID del Personaje");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 630, -1, -1));
        getContentPane().add(Tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(806, 628, 164, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID del Personaje");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 630, -1, -1));
        getContentPane().add(Tf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1144, 628, 164, -1));

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 659, -1, -1));

        jButton5.setText("Modificar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 659, -1, -1));

        jButton6.setText("Modificar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(806, 659, -1, -1));

        jButton8.setText("Modificar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1144, 659, -1, -1));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*   if (selecionar.showDialog(null, "Abrir") == JFileChooser.APPROVE_OPTION) {
        archivo = selecionar.getSelectedFile();
        //if(archivo.getName().endsWith("txt")){
        if (archivo.canRead()) {
        String Documento = AbrirArchivo(archivo);
        TxtArea.setText(Documento);
        } else {
        JOptionPane.showMessageDialog(null, "Archivo No Compatible");
        }   }*/
        Connection con = null;
        String Datos[] = new String[15];
        try {
            con = getConecction();

            ps = con.prepareStatement("SELECT a.nombre, a.edad, a.ciudad_de_origen,"
                    + "a.fecha_nacimiento, a.sexo, a.estatura, a.estado_civil, a.id_personaje,"
                    + "b.profesion, b.rasgo1,b.rasgo2,b.rasgo3,b.rasgo4,b.rasgo5, b.idioma"
                    + " from Personaje A inner join Personaje_2 B on a.id_personaje = b.id_personaje where a.id_personaje = ?");
            ps.setString(1, Tf.getText());
            rs = ps.executeQuery();

            if (rs.next()) {
                Datos[0] = ("Nombre : " + rs.getString("nombre") + "\n");
                Datos[1] = ("Edad : " + rs.getString("edad") + "\n");
                Datos[2] = ("Ciudad de Origen : " + rs.getString("ciudad_de_origen") + "\n");
                Datos[3] = ("Fechas de Nacimiento : " + rs.getString("fecha_nacimiento") + "\n");
                Datos[4] = ("Sexo : " + rs.getString("sexo") + "\n");
                Datos[5] = ("Estatura : " + rs.getString("estatura") + "\n");
                Datos[6] = ("Estado Civil : " + rs.getString("estado_civil") + "\n");
                Datos[7] = ("ID del Personaje : " + rs.getString("id_personaje").toString() + "\n");
                Datos[8] = ("Profesion : " + rs.getString("profesion") + "\n");
                Datos[9] = ("Rasgo 1 : " + rs.getString("rasgo1") + "\n");
                Datos[10] = ("Rasgo 2  : " + rs.getString("rasgo2") + "\n");
                Datos[11] = ("Rasgo 3  : " + rs.getString("rasgo3") + "\n");
                Datos[12] = ("Rasgo 4  : " + rs.getString("rasgo4") + "\n");
                Datos[13] = ("Rasgo 5  : " + rs.getString("rasgo5") + "\n");
                Datos[14] = ("Idiomas : " + rs.getString("idioma") + "\n");
                
                TxtA.setText(Datos[0]+Datos[1]+Datos[2]+Datos[3]+Datos[4]+Datos[5]
                +Datos[6]+Datos[7]+Datos[8]+Datos[9]+Datos[10]+Datos[11]
                +Datos[12]+Datos[13]+Datos[14]);
            } else {
                JOptionPane.showMessageDialog(null, "No existe un personaje con esa clave");
            }
        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public static Connection getConecction() {
        Connection con = null;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(URL, USERNAME, PASSWORD);
        } catch (Exception ex) {
            System.out.println(ex);
        }
        return con;
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     Connection con = null;
        String Datos[] = new String[15];
        try {
            con = getConecction();

            ps = con.prepareStatement("SELECT a.nombre, a.edad, a.ciudad_de_origen,"
                    + "a.fecha_nacimiento, a.sexo, a.estatura, a.estado_civil, a.id_personaje,"
                    + "b.profesion, b.rasgo1,b.rasgo2,b.rasgo3,b.rasgo4,b.rasgo5, b.idioma"
                    + " from Personaje A inner join Personaje_2 B on a.id_personaje = b.id_personaje where a.id_personaje = ?");
            ps.setString(1, Tf2.getText());
            rs = ps.executeQuery();

            if (rs.next()) {
                Datos[0] = ("Nombre : " + rs.getString("nombre") + "\n");
                Datos[1] = ("Edad : " + rs.getString("edad") + "\n");
                Datos[2] = ("Ciudad de Origen : " + rs.getString("ciudad_de_origen") + "\n");
                Datos[3] = ("Fechas de Nacimiento : " + rs.getString("fecha_nacimiento") + "\n");
                Datos[4] = ("Sexo : " + rs.getString("sexo") + "\n");
                Datos[5] = ("Estatura : " + rs.getString("estatura") + "\n");
                Datos[6] = ("Estado Civil : " + rs.getString("estado_civil") + "\n");
                Datos[7] = ("ID del Personaje : " + rs.getString("id_personaje").toString() + "\n");
                Datos[8] = ("Profesion : " + rs.getString("profesion") + "\n");
                Datos[9] = ("Rasgo 1 : " + rs.getString("rasgo1") + "\n");
                Datos[10] = ("Rasgo 2  : " + rs.getString("rasgo2") + "\n");
                Datos[11] = ("Rasgo 3  : " + rs.getString("rasgo3") + "\n");
                Datos[12] = ("Rasgo 4  : " + rs.getString("rasgo4") + "\n");
                Datos[13] = ("Rasgo 5  : " + rs.getString("rasgo5") + "\n");
                Datos[14] = ("Idiomas : " + rs.getString("idioma") + "\n");
                
                TxtA3.setText(Datos[0]+Datos[1]+Datos[2]+Datos[3]+Datos[4]+Datos[5]
                +Datos[6]+Datos[7]+Datos[8]+Datos[9]+Datos[10]+Datos[11]
                +Datos[12]+Datos[13]+Datos[14]);
            } else {
                JOptionPane.showMessageDialog(null, "No existe un personaje con esa clave");
            }
        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      Connection con = null;
        String Datos[] = new String[15];
        try {
            con = getConecction();

            ps = con.prepareStatement("SELECT a.nombre, a.edad, a.ciudad_de_origen,"
                    + "a.fecha_nacimiento, a.sexo, a.estatura, a.estado_civil, a.id_personaje,"
                    + "b.profesion, b.rasgo1,b.rasgo2,b.rasgo3,b.rasgo4,b.rasgo5, b.idioma"
                    + " from Personaje A inner join Personaje_2 B on a.id_personaje = b.id_personaje where a.id_personaje = ?");
            ps.setString(1, Tf3.getText());
            rs = ps.executeQuery();

            if (rs.next()) {
                Datos[0] = ("Nombre : " + rs.getString("nombre") + "\n");
                Datos[1] = ("Edad : " + rs.getString("edad") + "\n");
                Datos[2] = ("Ciudad de Origen : " + rs.getString("ciudad_de_origen") + "\n");
                Datos[3] = ("Fechas de Nacimiento : " + rs.getString("fecha_nacimiento") + "\n");
                Datos[4] = ("Sexo : " + rs.getString("sexo") + "\n");
                Datos[5] = ("Estatura : " + rs.getString("estatura") + "\n");
                Datos[6] = ("Estado Civil : " + rs.getString("estado_civil") + "\n");
                Datos[7] = ("ID del Personaje : " + rs.getString("id_personaje").toString() + "\n");
                Datos[8] = ("Profesion : " + rs.getString("profesion") + "\n");
                Datos[9] = ("Rasgo 1 : " + rs.getString("rasgo1") + "\n");
                Datos[10] = ("Rasgo 2  : " + rs.getString("rasgo2") + "\n");
                Datos[11] = ("Rasgo 3  : " + rs.getString("rasgo3") + "\n");
                Datos[12] = ("Rasgo 4  : " + rs.getString("rasgo4") + "\n");
                Datos[13] = ("Rasgo 5  : " + rs.getString("rasgo5") + "\n");
                Datos[14] = ("Idiomas : " + rs.getString("idioma") + "\n");
                
                TxtA4.setText(Datos[0]+Datos[1]+Datos[2]+Datos[3]+Datos[4]+Datos[5]
                +Datos[6]+Datos[7]+Datos[8]+Datos[9]+Datos[10]+Datos[11]
                +Datos[12]+Datos[13]+Datos[14]);
            } else {
                JOptionPane.showMessageDialog(null, "No existe un personaje con esa clave");
            }
        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
     Connection con = null;
        String Datos[] = new String[15];
        try {
            con = getConecction();

            ps = con.prepareStatement("SELECT a.nombre, a.edad, a.ciudad_de_origen,"
                    + "a.fecha_nacimiento, a.sexo, a.estatura, a.estado_civil, a.id_personaje,"
                    + "b.profesion, b.rasgo1,b.rasgo2,b.rasgo3,b.rasgo4,b.rasgo5, b.idioma"
                    + " from Personaje A inner join Personaje_2 B on a.id_personaje = b.id_personaje where a.id_personaje = ?");
            ps.setString(1, Tf1.getText());
            rs = ps.executeQuery();

            if (rs.next()) {
                Datos[0] = ("Nombre : " + rs.getString("nombre") + "\n");
                Datos[1] = ("Edad : " + rs.getString("edad") + "\n");
                Datos[2] = ("Ciudad de Origen : " + rs.getString("ciudad_de_origen") + "\n");
                Datos[3] = ("Fechas de Nacimiento : " + rs.getString("fecha_nacimiento") + "\n");
                Datos[4] = ("Sexo : " + rs.getString("sexo") + "\n");
                Datos[5] = ("Estatura : " + rs.getString("estatura") + "\n");
                Datos[6] = ("Estado Civil : " + rs.getString("estado_civil") + "\n");
                Datos[7] = ("ID del Personaje : " + rs.getString("id_personaje").toString() + "\n");
                Datos[8] = ("Profesion : " + rs.getString("profesion") + "\n");
                Datos[9] = ("Rasgo 1 : " + rs.getString("rasgo1") + "\n");
                Datos[10] = ("Rasgo 2  : " + rs.getString("rasgo2") + "\n");
                Datos[11] = ("Rasgo 3  : " + rs.getString("rasgo3") + "\n");
                Datos[12] = ("Rasgo 4  : " + rs.getString("rasgo4") + "\n");
                Datos[13] = ("Rasgo 5  : " + rs.getString("rasgo5") + "\n");
                Datos[14] = ("Idiomas : " + rs.getString("idioma") + "\n");
                
                TxtA2.setText(Datos[0]+Datos[1]+Datos[2]+Datos[3]+Datos[4]+Datos[5]
                +Datos[6]+Datos[7]+Datos[8]+Datos[9]+Datos[10]+Datos[11]
                +Datos[12]+Datos[13]+Datos[14]);
            } else {
                JOptionPane.showMessageDialog(null, "No existe un personaje con esa clave");
            }
        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        BarraDeCarga j = new BarraDeCarga();
        j.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    Connection con = null;
        try{
            
            con = getConecction();
            
ps = con.prepareStatement("UPDATE Personaje SET edad=?, estado_civil=? WHERE id_personaje=?"); //1 y 6
        String aux;
        aux = TxtA.getText();
        String Cad[] = aux.split("\n");
        String CadF[] = Cad[1].split(" ");
        String CadF2[] = Cad[6].split(" ");
        for (int i = 0; i < CadF2.length; i++) {
        
        System.out.println(CadF2[i]);
                
        }
        
        ps.setString(1, CadF[2]);
        ps.setString(2, CadF2[3]);
        ps.setString(3, Tf.getText());
        
            
        int Res = ps.executeUpdate();
        
        if (Res>0){
        JOptionPane.showMessageDialog(null, "Personaje Modificado");
        }else {
        JOptionPane.showMessageDialog(null, "Error al Modificar Personaje");
        }
            
            con.close();
        }
        catch(Exception e){
            System.out.println(e);
         JOptionPane.showMessageDialog(null, "Error al Modificar Personaje");
         JOptionPane.showMessageDialog(null, "Debe existir ya el Personaje");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Connection con = null;
        try{
            
            con = getConecction();
            
ps = con.prepareStatement("UPDATE Personaje SET edad=?, estado_civil=? WHERE id_personaje=?"); //1 y 6
        String aux;
        aux = TxtA2.getText();
        String Cad[] = aux.split("\n");
        String CadF[] = Cad[1].split(" ");
        String CadF2[] = Cad[6].split(" ");
        for (int i = 0; i < CadF2.length; i++) {
        
        System.out.println(CadF2[i]);
                
        }
        
        ps.setString(1, CadF[2]);
        ps.setString(2, CadF2[3]);
        ps.setString(3, Tf1.getText());
        
            
        int Res = ps.executeUpdate();
        
        if (Res>0){
        JOptionPane.showMessageDialog(null, "Personaje Modificado");
        }else {
        JOptionPane.showMessageDialog(null, "Error al Modificar Personaje");
        }
            
            con.close();
        }
        catch(Exception e){
            System.out.println(e);
         JOptionPane.showMessageDialog(null, "Error al Modificar Personaje");
         JOptionPane.showMessageDialog(null, "Debe existir ya el Personaje");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Connection con = null;
        try{
            
            con = getConecction();
            
ps = con.prepareStatement("UPDATE Personaje SET edad=?, estado_civil=? WHERE id_personaje=?"); //1 y 6
        String aux;
        aux = TxtA3.getText();
        String Cad[] = aux.split("\n");
        String CadF[] = Cad[1].split(" ");
        String CadF2[] = Cad[6].split(" ");
        for (int i = 0; i < CadF2.length; i++) {
        
        System.out.println(CadF2[i]);
                
        }
        
        ps.setString(1, CadF[2]);
        ps.setString(2, CadF2[3]);
        ps.setString(3, Tf2.getText());
        
            
        int Res = ps.executeUpdate();
        
        if (Res>0){
        JOptionPane.showMessageDialog(null, "Personaje Modificado");
        }else {
        JOptionPane.showMessageDialog(null, "Error al Modificar Personaje");
        }
            
            con.close();
        }
        catch(Exception e){
            System.out.println(e);
         JOptionPane.showMessageDialog(null, "Error al Modificar Personaje");
         JOptionPane.showMessageDialog(null, "Debe existir ya el Personaje");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Connection con = null;
        try{
            
            con = getConecction();
            
ps = con.prepareStatement("UPDATE Personaje SET edad=?, estado_civil=? WHERE id_personaje=?"); //1 y 6
        String aux;
        aux = TxtA4.getText();
        String Cad[] = aux.split("\n");
        String CadF[] = Cad[1].split(" ");
        String CadF2[] = Cad[6].split(" ");
        for (int i = 0; i < CadF2.length; i++) {
        
        System.out.println(CadF2[i]);
                
        }
        
        ps.setString(1, CadF[2]);
        ps.setString(2, CadF2[3]);
        ps.setString(3, Tf3.getText());
        
            
        int Res = ps.executeUpdate();
        
        if (Res>0){
        JOptionPane.showMessageDialog(null, "Personaje Modificado");
        }else {
        JOptionPane.showMessageDialog(null, "Error al Modificar Personaje");
        }
            
            con.close();
        }
        catch(Exception e){
            System.out.println(e);
         JOptionPane.showMessageDialog(null, "Error al Modificar Personaje");
         JOptionPane.showMessageDialog(null, "Debe existir ya el Personaje");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JTextField Tf;
    private javax.swing.JTextField Tf1;
    private javax.swing.JTextField Tf2;
    private javax.swing.JTextField Tf3;
    private javax.swing.JTextArea TxtA;
    private javax.swing.JTextArea TxtA2;
    private javax.swing.JTextArea TxtA3;
    private javax.swing.JTextArea TxtA4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane8;
    // End of variables declaration//GEN-END:variables
}
