/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zombie.world;

import java.awt.Cursor;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static zombie.world.Juego.getConecction;

/**
 *
 * @author Garabato
 */
public class Menu extends javax.swing.JFrame {
    /*para reproducir musica*/
public Clip clip;
public String ruta="/sonido/";
    /*hacer el cursos diferente*/
    Cursor cursor;
    ImageIcon img = new ImageIcon(getClass().getResource("/imagenes/mano.png"));
    Toolkit TK = Toolkit.getDefaultToolkit();

       
     //conexion a mysql
    public static final String URL = "jdbc:mysql://localhost:3306/zombieworld?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC";
    public static final String USERNAME = "root";
    public static final String PASSWORD = "root";
    PreparedStatement PS;
    
    public Menu() {
          //Cambiar icono
         this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/mano.png")).getImage());
        
        initComponents();
          /*parte de la musica*/sonido("Tili tili bom");
        this.setLocationRelativeTo(null);//centrar ventanas 
        /*parte del cursor diferente*/
        this.cursor = TK.createCustomCursor(img.getImage(), new Point(1, 1), "Cursor");
        this.setCursor(cursor);
        
        
    }
      public void sonido(String archivo){
     /*Parte de reproducir musica*/   
    try{
    clip = AudioSystem.getClip();
    clip.open(AudioSystem.getAudioInputStream(getClass().getResourceAsStream(ruta+archivo+".wav")));
    clip.start();}
    catch (LineUnavailableException | UnsupportedAudioFileException | IOException e){
     }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BtnCreditos = new javax.swing.JButton();
        BtnInstruccines = new javax.swing.JButton();
        BtnCrear = new javax.swing.JButton();
        Jugar = new javax.swing.JButton();
        BtnPG = new javax.swing.JButton();
        BtnPG2 = new javax.swing.JButton();
        BtnPG1 = new javax.swing.JButton();
        BtnRegistro = new javax.swing.JButton();
        MisterEggs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Instrucciones.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, 70));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("haz click en los dedos para cada funcion y click en la palma para jugar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 1170, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/creditos.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CrearPersonaje.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/jugar.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 180, 70));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Partidas Guardadas.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 440, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Registros.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 270, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Zombie.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        BtnCreditos.setText("jButton1");
        BtnCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreditosActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 30, 50));

        BtnInstruccines.setText("jButton1");
        BtnInstruccines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInstruccinesActionPerformed(evt);
            }
        });
        getContentPane().add(BtnInstruccines, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 110, 80));

        BtnCrear.setText("jButton1");
        BtnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 50, 130));

        Jugar.setText("jButton1");
        Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugarActionPerformed(evt);
            }
        });
        getContentPane().add(Jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 160, 160));

        BtnPG.setText("jButton1");
        BtnPG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPGActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPG, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 50, 50));

        BtnPG2.setText("jButton1");
        BtnPG2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPG2ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 40, 30));

        BtnPG1.setText("jButton1");
        BtnPG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPG1ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 60, 40));

        BtnRegistro.setText("jButton1");
        BtnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 40, 60));

        MisterEggs.setText("jButton1");
        MisterEggs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MisterEggsActionPerformed(evt);
            }
        });
        getContentPane().add(MisterEggs, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 680, 120, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnInstruccinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInstruccinesActionPerformed
        Instrucciones I = new Instrucciones();
        I.setVisible(true);
        this.dispose();
          clip.stop();
    }//GEN-LAST:event_BtnInstruccinesActionPerformed

    private void BtnCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreditosActionPerformed
        Creditos C = new Creditos();
        C.setVisible(true);
        this.dispose();
          clip.stop();
    }//GEN-LAST:event_BtnCreditosActionPerformed

    private void BtnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearActionPerformed
        CrearPersonaje CP = new CrearPersonaje();
        CP.setVisible(true);
        this.dispose();
          clip.stop();
    }//GEN-LAST:event_BtnCrearActionPerformed

    private void JugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugarActionPerformed
    Informacion B = new Informacion();
    B.setVisible(true);
    this.dispose();
      clip.stop(); //Opcional
    }//GEN-LAST:event_JugarActionPerformed

    private void BtnPGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPGActionPerformed
    PartidasGuardadas PG = new PartidasGuardadas();
    PG.setVisible(true);
    this.dispose();
      clip.stop();
    }//GEN-LAST:event_BtnPGActionPerformed

    private void BtnPG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPG1ActionPerformed
    PartidasGuardadas PG = new PartidasGuardadas();
    PG.setVisible(true);
    this.dispose();
     clip.stop(); 
    }//GEN-LAST:event_BtnPG1ActionPerformed

    private void BtnPG2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPG2ActionPerformed
    PartidasGuardadas PG = new PartidasGuardadas();
    PG.setVisible(true);
    this.dispose();
      clip.stop();
    }//GEN-LAST:event_BtnPG2ActionPerformed

    private void BtnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistroActionPerformed
    Registros R = new Registros();
    R.setVisible(true);
    this.dispose();
      clip.stop();
    }//GEN-LAST:event_BtnRegistroActionPerformed

    private void MisterEggsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MisterEggsActionPerformed
      Connection con = null;
      JOptionPane.showMessageDialog(null, "Enorabuena Mister Eggs DESBLOQUEADO");
        //RECURSOS
        try {

            con = getConecction();

            PS = con.prepareStatement("UPDATE MisterEggs SET Desbloqueado = 'Si'"
                    + " WHERE id_MisterEggs=2");

            int Res = PS.executeUpdate();

            if (Res > 0) {
            } else {
                JOptionPane.showMessageDialog(null, "Error Datos No Actualizados");
            }

            con.close();
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Error Datos No Actualizados");
            JOptionPane.showMessageDialog(null, "Debe existir ya el Personaje y llenar todos los datos");
        }
        
    }//GEN-LAST:event_MisterEggsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCrear;
    private javax.swing.JButton BtnCreditos;
    private javax.swing.JButton BtnInstruccines;
    private javax.swing.JButton BtnPG;
    private javax.swing.JButton BtnPG1;
    private javax.swing.JButton BtnPG2;
    private javax.swing.JButton BtnRegistro;
    private javax.swing.JButton Jugar;
    private javax.swing.JButton MisterEggs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
