/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zombie.world;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import javax.swing.JOptionPane;
import static zombie.world.Juego.getConecction;

/**
 *
 * @author Garabato
 */
public class PartidasGuardadas extends javax.swing.JFrame {

    public static final String URL = "jdbc:mysql://localhost:3306/zombieworld?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC";
    public static final String USERNAME = "root";
    public static final String PASSWORD = "root";
    PreparedStatement ps = null;
    ResultSet rs = null;

    /*hacer el cursos diferente*/
    Cursor cursor;
    ImageIcon img = new ImageIcon(getClass().getResource("/imagenes/mano.png"));
    Toolkit TK = Toolkit.getDefaultToolkit();

    public PartidasGuardadas() {
        //Cambiar icono
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/mano.png")).getImage());

        initComponents();
        this.setLocationRelativeTo(null);//centrar ventanas 
        /*parte del cursor diferente*/
        this.cursor = TK.createCustomCursor(img.getImage(), new Point(1, 1), "Cursor");
        this.setCursor(cursor);
        //IMAGEN DEL LABEL
        this.setLocationRelativeTo(null);
        ImageIcon imagen = new ImageIcon(getClass().getResource("/imagenes/5.jpg"));
        Icon Fondo = new ImageIcon(imagen.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
        jLabel1.setIcon(Fondo);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Tf = new javax.swing.JTextField();
        JB = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel2.setText("ID Base");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 50, 20));
        getContentPane().add(Tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 130, -1));

        JB.setText("Cargar");
        JB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBActionPerformed(evt);
            }
        });
        getContentPane().add(JB, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Atras.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 776, 452));

        TxtA.setEditable(false);
        TxtA.setBackground(new java.awt.Color(240, 240, 240));
        TxtA.setColumns(20);
        TxtA.setLineWrap(true);
        TxtA.setRows(5);
        TxtA.setBorder(null);
        TxtA.setOpaque(false);
        jScrollPane1.setViewportView(TxtA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 11, 517, 452));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBActionPerformed
        Connection con = null;
        String Datos[] = new String[24];
        try {
            con = getConecction();

            ps = con.prepareStatement("SELECT a.Agua, a.Comida, a.Combustible,"
                    + "a.Medicina, a.Municion, a.id_Base, b.Salud, b.Cordura,b.Confianza,c.nombre ,d.num_Personas,d.num_dias "
                    + "from Recursos A inner join SCC B on a.id_Base = b.id_Base "
                    + "inner join Personaje C on b.id_personaje = c.id_personaje "
                    + "inner join Base D on a.id_Base = d.id_Base where a.id_base = ?");
            ps.setString(1, Tf.getText());
            rs = ps.executeQuery();

            if (rs.next()) {
                Datos[0] = ("Cantidad de Agua : " + rs.getString("Agua") + "\n");
                Datos[1] = ("Cantidad de Comida : " + rs.getString("Comida") + "\n");
                Datos[2] = ("Cantidad de Combustible : " + rs.getString("Combustible") + "\n");
                Datos[3] = ("Cantidad de Medicina : " + rs.getString("Medicina") + "\n");
                Datos[4] = ("Cantidad de Municion : " + rs.getString("Municion") + "\n");
                Datos[5] = ("ID de Base : " + rs.getString("Id_Base") + "\n");
                Datos[6] = ("Salud : " + rs.getString("Salud") + "\n");
                Datos[7] = ("Cordura : " + rs.getString("Cordura") + "\n");
                Datos[8] = ("Confianza : " + rs.getString("Confianza") + "\n");
                Datos[9] = ("Nombre del Personaje : " + rs.getString("nombre") + "\n");
                Datos[22] = ("Numero de personas en la Comunidad : " + rs.getString("num_Personas") + "\n");
                Datos[23] = ("Numero de Dias Transcurridos : " + rs.getString("num_dias") + "\n");
                int x = 10;
                while (rs.next()) {

                    Datos[x] = ("Salud : " + rs.getString("Salud") + "\n");
                    Datos[x + 1] = ("Cordura : " + rs.getString("Cordura") + "\n");
                    Datos[x + 2] = ("Confianza : " + rs.getString("Confianza") + "\n");
                    Datos[x + 3] = ("Nombre del Personaje : " + rs.getString("nombre") + "\n");
                    x = x + 4;
                }

                TxtA.setText(Datos[0] + Datos[1] + Datos[2] + Datos[3] + Datos[4] + Datos[5]
                        + "Personaje 1 \n" + Datos[9] + Datos[6] + Datos[7] + Datos[8]
                        + "Personaje 2 \n" + Datos[13] + Datos[10] + Datos[11] + Datos[12]
                        + "Personaje 3 \n" + Datos[17] + Datos[14] + Datos[15] + Datos[16]
                        + "Personaje 4 \n" + Datos[21] + Datos[18] + Datos[19] + Datos[20]
                        + Datos[22] + Datos[23]);
            } else {
                JOptionPane.showMessageDialog(null, "No existe un personaje con esa clave");
            }
        } catch (Exception e) {
            System.err.println(e);
        }
    }

    public static Connection getConecction() {
        Connection con = null;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(URL, USERNAME, PASSWORD);
        } catch (Exception ex) {
            System.out.println(ex);
        }
        return con;
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {

    }//GEN-LAST:event_JBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      Menu M = new Menu();
        M.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PartidasGuardadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PartidasGuardadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PartidasGuardadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PartidasGuardadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PartidasGuardadas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB;
    private javax.swing.JTextField Tf;
    private javax.swing.JTextArea TxtA;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
