/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zombie.world;
import java.awt.Cursor;
import java.awt.Point;
import java.awt.Toolkit;
import java.sql.*;        
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static zombie.world.Inventarios.PASSWORD;
import static zombie.world.Inventarios.URL;
import static zombie.world.Inventarios.USERNAME;
import static zombie.world.Inventarios.getConecction;

/**
 *
 * @author Garabato
 */
public class Registros extends javax.swing.JFrame {
  
  /*hacer el cursos diferente*/
    Cursor cursor;
    ImageIcon img = new ImageIcon(getClass().getResource("/imagenes/EspadaImperial.png"));
    Toolkit TK = Toolkit.getDefaultToolkit();

    //conexion a mysql
    public static final String URL = "jdbc:mysql://localhost:3306/zombieworld?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC";
    public static final String USERNAME = "root";
    public static final String PASSWORD = "root";
    public Registros() {
        initComponents();
        Cont.setText("0"); //   CONTADOR CHIDO
        Cont2.setText("0"); //   CONTADOR CHIDO
        Cont3.setText("0"); //   CONTADOR CHIDO
        Cont4.setText("0"); //   CONTADOR CHIDO
        this.setLocationRelativeTo(null);
        //Cambiar icono
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/mano.png")).getImage());
    /*parte del cursor diferente*/
        this.cursor = TK.createCustomCursor(img.getImage(), new Point(1, 1), "Cursor");
        this.setCursor(cursor);
          
            Connection con = getConecction();
            CallableStatement CS;
             ResultSet rs = null;
        try {
               CS = con.prepareCall("select Contar_personaje() as tabla_A;");
              rs = CS.executeQuery();
              
              if (rs.next()){
              Txf.setText(rs.getString("Tabla_A"));
              }

        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
        try {
               CS = con.prepareCall("select Contar_Base() as tabla_A;");
              rs = CS.executeQuery();
              
              if (rs.next()){
              Txf1.setText(rs.getString("Tabla_A"));
              }

        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
        try {
               CS = con.prepareCall("select Contar_Armas() as tabla_A;");
              rs = CS.executeQuery();
              
              if (rs.next()){
              Txf2.setText(rs.getString("Tabla_A"));
              }

        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
        try {
               CS = con.prepareCall("select Contar_Vehiculos() as tabla_A;");
              rs = CS.executeQuery();
              
              if (rs.next()){
              Txf3.setText(rs.getString("Tabla_A"));
              }

        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
        
    }
    
    
    
        public static Connection getConecction() {
        Connection con = null;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(URL, USERNAME, PASSWORD);

        } catch (Exception ex) {
            System.out.println(ex);
        }
        return con;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Txf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Txf1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Txf2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Txf3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JT = new javax.swing.JTable();
        Cont = new javax.swing.JLabel();
        Cont2 = new javax.swing.JLabel();
        Cont3 = new javax.swing.JLabel();
        Cont4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Eliminar Todos los Personaje");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, 30));

        Txf.setEditable(false);
        Txf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxfMouseClicked(evt);
            }
        });
        Txf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxfActionPerformed(evt);
            }
        });
        getContentPane().add(Txf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 60, -1));

        jLabel1.setText("Numero de Personajes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 130, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Atras.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 60, 30));

        jLabel3.setText("Numero de Bases");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, -1));

        Txf1.setEditable(false);
        Txf1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Txf1MouseClicked(evt);
            }
        });
        getContentPane().add(Txf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 60, -1));

        jLabel4.setText("Armas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, -1));

        Txf2.setEditable(false);
        Txf2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Txf2MouseClicked(evt);
            }
        });
        getContentPane().add(Txf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 60, -1));

        jLabel5.setText("Vehiculos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 130, -1));

        Txf3.setEditable(false);
        Txf3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Txf3MouseClicked(evt);
            }
        });
        getContentPane().add(Txf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 60, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Horda2.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        JT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JT);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 570, 330));

        Cont.setText("jLabel4");
        getContentPane().add(Cont, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        Cont2.setText("jLabel4");
        getContentPane().add(Cont2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        Cont3.setText("jLabel4");
        getContentPane().add(Cont3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        Cont4.setText("jLabel4");
        getContentPane().add(Cont4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            try {
                DefaultTableModel modelo = new DefaultTableModel();
                PreparedStatement ps = null;
            ResultSet rs = null;
            Connection con = getConecction(); 
           CallableStatement CS; 
                CS = con.prepareCall("call Eliminar_Personajes");
              rs = CS.executeQuery();
            JOptionPane.showMessageDialog(null, "Personajes eliminados correctamente");
            try {
               CS = con.prepareCall("select Contar_personaje() as tabla_A;");
              rs = CS.executeQuery();
              
              if (rs.next()){
              Txf.setText(rs.getString("Tabla_A"));
              }

        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }

        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Menu M = new Menu();
        M.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TxfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxfMouseClicked
       DefaultTableModel modelo = new DefaultTableModel();
        String cont = Cont.getText();
        String where = "";
         where = "WHERE Edad != 0";
         
       if (cont.equals("0")){
        Cont.setText("1");
        Cont2.setText("0");
        Cont4.setText("0");
        Cont3.setText("0");
        try {
            JT.setModel(modelo);

            PreparedStatement ps = null;
            ResultSet rs = null;
            Connection con = getConecction();

            String sql = "SELECT nombre, edad from Personaje " + where;

            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumna = rsMd.getColumnCount();
            modelo.addColumn("Nombre");
            modelo.addColumn("Edad");

            while (rs.next()) {

                Object[] filas = new Object[cantidadColumna];
                for (int i = 0; i < cantidadColumna; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);

            }

        } catch (SQLException ex) {
            System.out.println(ex.toString());
        } } else {
       }
    }//GEN-LAST:event_TxfMouseClicked

    private void TxfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxfActionPerformed

    private void Txf1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txf1MouseClicked
        DefaultTableModel modelo = new DefaultTableModel();
        String cont = Cont2.getText();
       if (cont.equals("0")){
        Cont2.setText("1");
        Cont.setText("0");
        Cont3.setText("0");
        Cont4.setText("0");
        try {
            JT.setModel(modelo);

            PreparedStatement ps = null;
            ResultSet rs = null;
            Connection con = getConecction();

            String sql = "SELECT id_Base,Num_Personas,Num_Dias FROM Base ";

            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumna = rsMd.getColumnCount();
            modelo.addColumn("id_Base");
            modelo.addColumn("Num_Personas");
            modelo.addColumn("Num_Dias");

            while (rs.next()) {

                Object[] filas = new Object[cantidadColumna];
                for (int i = 0; i < cantidadColumna; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);

            }

        } catch (SQLException ex) {
            System.out.println(ex.toString());
        } } else {
       
       }
    }//GEN-LAST:event_Txf1MouseClicked

    private void Txf2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txf2MouseClicked
     DefaultTableModel modelo = new DefaultTableModel();
        String cont = Cont3.getText();
       if (cont.equals("0")){
        Cont3.setText("1");
        Cont.setText("0");
        Cont2.setText("0");
        Cont4.setText("0");
        try {
            JT.setModel(modelo);

            PreparedStatement ps = null;
            ResultSet rs = null;
            Connection con = getConecction();

            String sql = "SELECT * FROM Armas ";

            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumna = rsMd.getColumnCount();
            modelo.addColumn("id_Armas");
            modelo.addColumn("Nombre");
            modelo.addColumn("Daño_Adic");
            modelo.addColumn("Consumo");

            while (rs.next()) {

                Object[] filas = new Object[cantidadColumna];
                for (int i = 0; i < cantidadColumna; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);

            }

        } catch (SQLException ex) {
            System.out.println(ex.toString());
        } } else {
       
       }
    }//GEN-LAST:event_Txf2MouseClicked

    private void Txf3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txf3MouseClicked
     DefaultTableModel modelo = new DefaultTableModel();
        String cont = Cont4.getText();
       if (cont.equals("0")){
        Cont4.setText("1");
        Cont.setText("0");
        Cont2.setText("0");
        Cont3.setText("0");
        try {
            JT.setModel(modelo);

            PreparedStatement ps = null;
            ResultSet rs = null;
            Connection con = getConecction();

            String sql = "SELECT * FROM Vehiculos ";

            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumna = rsMd.getColumnCount();
            modelo.addColumn("id_Vehiculos");
            modelo.addColumn("Nombre_Vehiculo");
            modelo.addColumn("Consumo_Dia");
            modelo.addColumn("Consumo_Hora");

            while (rs.next()) {

                Object[] filas = new Object[cantidadColumna];
                for (int i = 0; i < cantidadColumna; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);

            }

        } catch (SQLException ex) {
            System.out.println(ex.toString());
        } } else {
       
       }
    }//GEN-LAST:event_Txf3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cont;
    private javax.swing.JLabel Cont2;
    private javax.swing.JLabel Cont3;
    private javax.swing.JLabel Cont4;
    private javax.swing.JTable JT;
    private javax.swing.JTextField Txf;
    private javax.swing.JTextField Txf1;
    private javax.swing.JTextField Txf2;
    private javax.swing.JTextField Txf3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
